### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by martinaust** [alexe13/PrimeDiceBot#1]
Hi,

could you please add the feature, that I can set a new roll target after a specific loss streak? 

For example: after 20 losses in a row, the roll target ist set to an easier target (like 50.00) and everything else remains.

That would be very usefull, because of overall loss reduction!

**Comment by alexe13** [comment]
Hi, 

I haven't updated this project for a while now, but I think I can implement this feature in a free time. Please check back in a week or so.

**Comment by martinaust** [comment]
Great news! 

Please also remove your API key from the .class files (you can view them while open the .jar with JD GUI) because it seems, its your productive key.

**Comment by alexe13** [comment]
I ended up adding a target adjustment on loose streaks. For example, if your initial target is <50, target adjustment is +5 and you reach a specified number of loose streaks, on each consequent loose target will be adjusted for 5, e.g <55, <60 etc, making it easier with every loose. On wins it will gradually recover to the initial target. It allows more flexible adjustment, limiting devastating loose streaks without loosing too much profit. I uploaded updated release but did not have enough time to test all possible option combinations so please use carefully.

**Comment by martinaust** [comment]
Target adjustment works fine so far, but there might be a little misfunction. 

Example: maxLosseStreak = 10

When reaching 10 Losses, you have to adjust the Target like the setup (e.g. -5) as long as you WIN. When winning after a an adjustment was made, the Bot should return to the base Target and stops the adjustment until the next 10 Losses occur.

I hope you know what I mean. Nevertheless great work!
