### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by martinaust** [alexe13/PrimeDiceBot#2]
Target adjustment works fine so far, but there might be a little misfunction.

Example: maxLosseStreak = 10

When reaching 10 Losses, you have to adjust the Target like the setup (e.g. -5) as long as you WIN. When winning after a an adjustment was made, the Bot should return to the base Target and stops the adjustment until the next 10 Losses occur.

I hope you know what I mean. Nevertheless great work!

**Comment by alexe13** [comment]
Are you rolling with ">" or "<" condition?

I just stumbled upon a bug with ">" condition when adjustment didn't stop after loose streak ended.
Will try to fix asap, but for now use "<" condition - it should work fine.

**Comment by martinaust** [comment]
Yes you are right! By setting the condition to "<" it works fine :)

**Comment by alexe13** [comment]
The bug should be gone now.
